// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Variable_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FunctionDecl struct {
	_tab flatbuffers.Table
}

func GetRootAsFunctionDecl(buf []byte, offset flatbuffers.UOffsetT) *FunctionDecl {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FunctionDecl{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FunctionDecl) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FunctionDecl) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FunctionDecl) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FunctionDecl) Location() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FunctionDeclStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FunctionDeclAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func FunctionDeclAddLocation(builder *flatbuffers.Builder, location flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(location), 0)
}
func FunctionDeclEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
