image:
  file: docker/Dockerfile
tasks:
  - init: . .bashrc
  - command: cd ${HOME}/fastseq/nucleus && bazel build -c opt ${COPT_FLAGS} nucleus/examples:all
vscode:
  extensions:
    - jebbs.plantuml@2.13.9:Kh1501AVTKuUtjU0w5lOEQ==
