image:
  file: Dockerfile
tasks:
  - init: . .bashrc
  - command: ./bin/install-nucleus.sh
github:
  prebuilds:
    master: true
    branches: true  
vscode:
  extensions:
    - jebbs.plantuml@2.13.9:Kh1501AVTKuUtjU0w5lOEQ==
