image:
  file: docker/Dockerfile
tasks:
  - init: . .bashrc
  - command: patch -p1 /home/gitpod/nucleus/third_party/clif.bzl < clif.bzl.patch && cd /home/gitpod/nucleus && bazel build -c opt ${COPT_FLAGS} nucleus/...
github:
  prebuilds:
    master: true
    branches: true  
vscode:
  extensions:
    - jebbs.plantuml@2.13.9:Kh1501AVTKuUtjU0w5lOEQ==
