// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Unit_

type LanguageType = int32
const (
	LanguageTypeDUMMY LanguageType = 0
	LanguageTypeALL LanguageType = 1
	LanguageTypeOO LanguageType = 2
	LanguageTypeCXX LanguageType = 3
	LanguageTypeC LanguageType = 4
	LanguageTypeC_FAMILY LanguageType = 5
	LanguageTypeJAVA LanguageType = 6
	LanguageTypeCSHARP LanguageType = 7
	LanguageTypeOBJECTIVE_C LanguageType = 8
	LanguageTypeSMALI LanguageType = 9
	LanguageTypeSOLIDITY LanguageType = 10
	LanguageTypeCOBOL85 LanguageType = 11
	LanguageTypePYTHON3 LanguageType = 12
)

var EnumNamesLanguageType = map[LanguageType]string{
	LanguageTypeDUMMY:"DUMMY",
	LanguageTypeALL:"ALL",
	LanguageTypeOO:"OO",
	LanguageTypeCXX:"CXX",
	LanguageTypeC:"C",
	LanguageTypeC_FAMILY:"C_FAMILY",
	LanguageTypeJAVA:"JAVA",
	LanguageTypeCSHARP:"CSHARP",
	LanguageTypeOBJECTIVE_C:"OBJECTIVE_C",
	LanguageTypeSMALI:"SMALI",
	LanguageTypeSOLIDITY:"SOLIDITY",
	LanguageTypeCOBOL85:"COBOL85",
	LanguageTypePYTHON3:"PYTHON3",
}

