// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Literal_

type LiteralType = int32
const (
	LiteralTypedummy_type LiteralType = 0
	LiteralTypenumber_type LiteralType = 1
	LiteralTypechar_type LiteralType = 2
	LiteralTypestring_type LiteralType = 3
	LiteralTypeboolean_type LiteralType = 4
	LiteralTypenull_type LiteralType = 5
)

var EnumNamesLiteralType = map[LiteralType]string{
	LiteralTypedummy_type:"dummy_type",
	LiteralTypenumber_type:"number_type",
	LiteralTypechar_type:"char_type",
	LiteralTypestring_type:"string_type",
	LiteralTypeboolean_type:"boolean_type",
	LiteralTypenull_type:"null_type",
}

