// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Slice_

type ChangeType = int32
const (
	ChangeTypeUNCHANGED ChangeType = 0
	ChangeTypeADD ChangeType = 1
	ChangeTypeDEL ChangeType = 2
)

var EnumNamesChangeType = map[ChangeType]string{
	ChangeTypeUNCHANGED:"UNCHANGED",
	ChangeTypeADD:"ADD",
	ChangeTypeDEL:"DEL",
}

