// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fast_

import (
	flatbuffers "github.com/google/flatbuffers/go"

	fast___Bugs_ "fast_/Bugs_"
)

type Bugs struct {
	_tab flatbuffers.Table
}

func GetRootAsBugs(buf []byte, offset flatbuffers.UOffsetT) *Bugs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Bugs{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Bugs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Bugs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Bugs) Repository() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Bugs) Bug(obj *fast___Bugs_.Bug, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Bugs) BugLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BugsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BugsAddRepository(builder *flatbuffers.Builder, repository flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(repository), 0)
}
func BugsAddBug(builder *flatbuffers.Builder, bug flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(bug), 0)
}
func BugsStartBugVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BugsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
