// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fast_

type Cobol85Kind = int32
const (
	Cobol85Kindstartrule Cobol85Kind = 0
	Cobol85Kindcompilationunit Cobol85Kind = 1
	Cobol85Kindprogramunit Cobol85Kind = 2
	Cobol85Kindendprogramstatement Cobol85Kind = 3
	Cobol85Kindidentificationdivision Cobol85Kind = 4
	Cobol85Kindidentificationdivisionbody Cobol85Kind = 5
	Cobol85Kindprogramidparagraph Cobol85Kind = 6
	Cobol85Kindauthorparagraph Cobol85Kind = 7
	Cobol85Kindinstallationparagraph Cobol85Kind = 8
	Cobol85Kinddatewrittenparagraph Cobol85Kind = 9
	Cobol85Kinddatecompiledparagraph Cobol85Kind = 10
	Cobol85Kindsecurityparagraph Cobol85Kind = 11
	Cobol85Kindremarksparagraph Cobol85Kind = 12
	Cobol85Kindenvironmentdivision Cobol85Kind = 13
	Cobol85Kindenvironmentdivisionbody Cobol85Kind = 14
	Cobol85Kindconfigurationsection Cobol85Kind = 15
	Cobol85Kindconfigurationsectionparagraph Cobol85Kind = 16
	Cobol85Kindsourcecomputerparagraph Cobol85Kind = 17
	Cobol85Kindobjectcomputerparagraph Cobol85Kind = 18
	Cobol85Kindobjectcomputerclause Cobol85Kind = 19
	Cobol85Kindmemorysizeclause Cobol85Kind = 20
	Cobol85Kinddisksizeclause Cobol85Kind = 21
	Cobol85Kindcollatingsequenceclause Cobol85Kind = 22
	Cobol85Kindcollatingsequenceclausealphanumeric Cobol85Kind = 23
	Cobol85Kindcollatingsequenceclausenational Cobol85Kind = 24
	Cobol85Kindsegmentlimitclause Cobol85Kind = 25
	Cobol85Kindcharactersetclause Cobol85Kind = 26
	Cobol85Kindspecialnamesparagraph Cobol85Kind = 27
	Cobol85Kindspecialnameclause Cobol85Kind = 28
	Cobol85Kindalphabetclause Cobol85Kind = 29
	Cobol85Kindalphabetclauseformat1 Cobol85Kind = 30
	Cobol85Kindalphabetliterals Cobol85Kind = 31
	Cobol85Kindalphabetthrough Cobol85Kind = 32
	Cobol85Kindalphabetalso Cobol85Kind = 33
	Cobol85Kindalphabetclauseformat2 Cobol85Kind = 34
	Cobol85Kindchannelclause Cobol85Kind = 35
	Cobol85Kindclassclause Cobol85Kind = 36
	Cobol85Kindclassclausethrough Cobol85Kind = 37
	Cobol85Kindclassclausefrom Cobol85Kind = 38
	Cobol85Kindclassclauseto Cobol85Kind = 39
	Cobol85Kindcurrencysignclause Cobol85Kind = 40
	Cobol85Kinddecimalpointclause Cobol85Kind = 41
	Cobol85Kinddefaultcomputationalsignclause Cobol85Kind = 42
	Cobol85Kinddefaultdisplaysignclause Cobol85Kind = 43
	Cobol85Kindenvironmentswitchnameclause Cobol85Kind = 44
	Cobol85Kindenvironmentswitchnamespecialnamesstatusphrase Cobol85Kind = 45
	Cobol85Kindodtclause Cobol85Kind = 46
	Cobol85Kindreservenetworkclause Cobol85Kind = 47
	Cobol85Kindsymboliccharactersclause Cobol85Kind = 48
	Cobol85Kindsymboliccharacters Cobol85Kind = 49
	Cobol85Kindinputoutputsection Cobol85Kind = 50
	Cobol85Kindinputoutputsectionparagraph Cobol85Kind = 51
	Cobol85Kindfilecontrolparagraph Cobol85Kind = 52
	Cobol85Kindfilecontrolentry Cobol85Kind = 53
	Cobol85Kindselectclause Cobol85Kind = 54
	Cobol85Kindfilecontrolclause Cobol85Kind = 55
	Cobol85Kindassignclause Cobol85Kind = 56
	Cobol85Kindreserveclause Cobol85Kind = 57
	Cobol85Kindorganizationclause Cobol85Kind = 58
	Cobol85Kindpaddingcharacterclause Cobol85Kind = 59
	Cobol85Kindrecorddelimiterclause Cobol85Kind = 60
	Cobol85Kindaccessmodeclause Cobol85Kind = 61
	Cobol85Kindrecordkeyclause Cobol85Kind = 62
	Cobol85Kindalternaterecordkeyclause Cobol85Kind = 63
	Cobol85Kindpasswordclause Cobol85Kind = 64
	Cobol85Kindfilestatusclause Cobol85Kind = 65
	Cobol85Kindrelativekeyclause Cobol85Kind = 66
	Cobol85Kindiocontrolparagraph Cobol85Kind = 67
	Cobol85Kindiocontrolclause Cobol85Kind = 68
	Cobol85Kindrerunclause Cobol85Kind = 69
	Cobol85Kindreruneveryrecords Cobol85Kind = 70
	Cobol85Kindreruneveryof Cobol85Kind = 71
	Cobol85Kindreruneveryclock Cobol85Kind = 72
	Cobol85Kindsameclause Cobol85Kind = 73
	Cobol85Kindmultiplefileclause Cobol85Kind = 74
	Cobol85Kindmultiplefileposition Cobol85Kind = 75
	Cobol85Kindcommitmentcontrolclause Cobol85Kind = 76
	Cobol85Kinddatadivision Cobol85Kind = 77
	Cobol85Kinddatadivisionsection Cobol85Kind = 78
	Cobol85Kindfilesection Cobol85Kind = 79
	Cobol85Kindfiledescriptionentry Cobol85Kind = 80
	Cobol85Kindfiledescriptionentryclause Cobol85Kind = 81
	Cobol85Kindexternalclause Cobol85Kind = 82
	Cobol85Kindglobalclause Cobol85Kind = 83
	Cobol85Kindblockcontainsclause Cobol85Kind = 84
	Cobol85Kindblockcontainsto Cobol85Kind = 85
	Cobol85Kindrecordcontainsclause Cobol85Kind = 86
	Cobol85Kindrecordcontainsclauseformat1 Cobol85Kind = 87
	Cobol85Kindrecordcontainsclauseformat2 Cobol85Kind = 88
	Cobol85Kindrecordcontainsclauseformat3 Cobol85Kind = 89
	Cobol85Kindrecordcontainsto Cobol85Kind = 90
	Cobol85Kindlabelrecordsclause Cobol85Kind = 91
	Cobol85Kindvalueofclause Cobol85Kind = 92
	Cobol85Kindvaluepair Cobol85Kind = 93
	Cobol85Kinddatarecordsclause Cobol85Kind = 94
	Cobol85Kindlinageclause Cobol85Kind = 95
	Cobol85Kindlinageat Cobol85Kind = 96
	Cobol85Kindlinagefootingat Cobol85Kind = 97
	Cobol85Kindlinagelinesattop Cobol85Kind = 98
	Cobol85Kindlinagelinesatbottom Cobol85Kind = 99
	Cobol85Kindrecordingmodeclause Cobol85Kind = 100
	Cobol85Kindmodestatement Cobol85Kind = 101
	Cobol85Kindcodesetclause Cobol85Kind = 102
	Cobol85Kindreportclause Cobol85Kind = 103
	Cobol85Kinddatabasesection Cobol85Kind = 104
	Cobol85Kinddatabasesectionentry Cobol85Kind = 105
	Cobol85Kindworkingstoragesection Cobol85Kind = 106
	Cobol85Kindlinkagesection Cobol85Kind = 107
	Cobol85Kindcommunicationsection Cobol85Kind = 108
	Cobol85Kindcommunicationdescriptionentry Cobol85Kind = 109
	Cobol85Kindcommunicationdescriptionentryformat1 Cobol85Kind = 110
	Cobol85Kindcommunicationdescriptionentryformat2 Cobol85Kind = 111
	Cobol85Kindcommunicationdescriptionentryformat3 Cobol85Kind = 112
	Cobol85Kinddestinationcountclause Cobol85Kind = 113
	Cobol85Kinddestinationtableclause Cobol85Kind = 114
	Cobol85Kindendkeyclause Cobol85Kind = 115
	Cobol85Kinderrorkeyclause Cobol85Kind = 116
	Cobol85Kindmessagecountclause Cobol85Kind = 117
	Cobol85Kindmessagedateclause Cobol85Kind = 118
	Cobol85Kindmessagetimeclause Cobol85Kind = 119
	Cobol85Kindstatuskeyclause Cobol85Kind = 120
	Cobol85Kindsymbolicdestinationclause Cobol85Kind = 121
	Cobol85Kindsymbolicqueueclause Cobol85Kind = 122
	Cobol85Kindsymbolicsourceclause Cobol85Kind = 123
	Cobol85Kindsymbolicterminalclause Cobol85Kind = 124
	Cobol85Kindsymbolicsubqueueclause Cobol85Kind = 125
	Cobol85Kindtextlengthclause Cobol85Kind = 126
	Cobol85Kindlocalstoragesection Cobol85Kind = 127
	Cobol85Kindscreensection Cobol85Kind = 128
	Cobol85Kindscreendescriptionentry Cobol85Kind = 129
	Cobol85Kindscreendescriptionblankclause Cobol85Kind = 130
	Cobol85Kindscreendescriptionbellclause Cobol85Kind = 131
	Cobol85Kindscreendescriptionblinkclause Cobol85Kind = 132
	Cobol85Kindscreendescriptioneraseclause Cobol85Kind = 133
	Cobol85Kindscreendescriptionlightclause Cobol85Kind = 134
	Cobol85Kindscreendescriptiongridclause Cobol85Kind = 135
	Cobol85Kindscreendescriptionreversevideoclause Cobol85Kind = 136
	Cobol85Kindscreendescriptionunderlineclause Cobol85Kind = 137
	Cobol85Kindscreendescriptionsizeclause Cobol85Kind = 138
	Cobol85Kindscreendescriptionlineclause Cobol85Kind = 139
	Cobol85Kindscreendescriptioncolumnclause Cobol85Kind = 140
	Cobol85Kindscreendescriptionforegroundcolorclause Cobol85Kind = 141
	Cobol85Kindscreendescriptionbackgroundcolorclause Cobol85Kind = 142
	Cobol85Kindscreendescriptioncontrolclause Cobol85Kind = 143
	Cobol85Kindscreendescriptionvalueclause Cobol85Kind = 144
	Cobol85Kindscreendescriptionpictureclause Cobol85Kind = 145
	Cobol85Kindscreendescriptionfromclause Cobol85Kind = 146
	Cobol85Kindscreendescriptiontoclause Cobol85Kind = 147
	Cobol85Kindscreendescriptionusingclause Cobol85Kind = 148
	Cobol85Kindscreendescriptionusageclause Cobol85Kind = 149
	Cobol85Kindscreendescriptionblankwhenzeroclause Cobol85Kind = 150
	Cobol85Kindscreendescriptionjustifiedclause Cobol85Kind = 151
	Cobol85Kindscreendescriptionsignclause Cobol85Kind = 152
	Cobol85Kindscreendescriptionautoclause Cobol85Kind = 153
	Cobol85Kindscreendescriptionsecureclause Cobol85Kind = 154
	Cobol85Kindscreendescriptionrequiredclause Cobol85Kind = 155
	Cobol85Kindscreendescriptionpromptclause Cobol85Kind = 156
	Cobol85Kindscreendescriptionpromptoccursclause Cobol85Kind = 157
	Cobol85Kindscreendescriptionfullclause Cobol85Kind = 158
	Cobol85Kindscreendescriptionzerofillclause Cobol85Kind = 159
	Cobol85Kindreportsection Cobol85Kind = 160
	Cobol85Kindreportdescription Cobol85Kind = 161
	Cobol85Kindreportdescriptionentry Cobol85Kind = 162
	Cobol85Kindreportdescriptionglobalclause Cobol85Kind = 163
	Cobol85Kindreportdescriptionpagelimitclause Cobol85Kind = 164
	Cobol85Kindreportdescriptionheadingclause Cobol85Kind = 165
	Cobol85Kindreportdescriptionfirstdetailclause Cobol85Kind = 166
	Cobol85Kindreportdescriptionlastdetailclause Cobol85Kind = 167
	Cobol85Kindreportdescriptionfootingclause Cobol85Kind = 168
	Cobol85Kindreportgroupdescriptionentry Cobol85Kind = 169
	Cobol85Kindreportgroupdescriptionentryformat1 Cobol85Kind = 170
	Cobol85Kindreportgroupdescriptionentryformat2 Cobol85Kind = 171
	Cobol85Kindreportgroupdescriptionentryformat3 Cobol85Kind = 172
	Cobol85Kindreportgroupblankwhenzeroclause Cobol85Kind = 173
	Cobol85Kindreportgroupcolumnnumberclause Cobol85Kind = 174
	Cobol85Kindreportgroupindicateclause Cobol85Kind = 175
	Cobol85Kindreportgroupjustifiedclause Cobol85Kind = 176
	Cobol85Kindreportgrouplinenumberclause Cobol85Kind = 177
	Cobol85Kindreportgrouplinenumbernextpage Cobol85Kind = 178
	Cobol85Kindreportgrouplinenumberplus Cobol85Kind = 179
	Cobol85Kindreportgroupnextgroupclause Cobol85Kind = 180
	Cobol85Kindreportgroupnextgroupplus Cobol85Kind = 181
	Cobol85Kindreportgroupnextgroupnextpage Cobol85Kind = 182
	Cobol85Kindreportgrouppictureclause Cobol85Kind = 183
	Cobol85Kindreportgroupresetclause Cobol85Kind = 184
	Cobol85Kindreportgroupsignclause Cobol85Kind = 185
	Cobol85Kindreportgroupsourceclause Cobol85Kind = 186
	Cobol85Kindreportgroupsumclause Cobol85Kind = 187
	Cobol85Kindreportgrouptypeclause Cobol85Kind = 188
	Cobol85Kindreportgrouptypereportheading Cobol85Kind = 189
	Cobol85Kindreportgrouptypepageheading Cobol85Kind = 190
	Cobol85Kindreportgrouptypecontrolheading Cobol85Kind = 191
	Cobol85Kindreportgrouptypedetail Cobol85Kind = 192
	Cobol85Kindreportgrouptypecontrolfooting Cobol85Kind = 193
	Cobol85Kindreportgroupusageclause Cobol85Kind = 194
	Cobol85Kindreportgrouptypepagefooting Cobol85Kind = 195
	Cobol85Kindreportgrouptypereportfooting Cobol85Kind = 196
	Cobol85Kindreportgroupvalueclause Cobol85Kind = 197
	Cobol85Kindprogramlibrarysection Cobol85Kind = 198
	Cobol85Kindlibrarydescriptionentry Cobol85Kind = 199
	Cobol85Kindlibrarydescriptionentryformat1 Cobol85Kind = 200
	Cobol85Kindlibrarydescriptionentryformat2 Cobol85Kind = 201
	Cobol85Kindlibraryattributeclauseformat1 Cobol85Kind = 202
	Cobol85Kindlibraryattributeclauseformat2 Cobol85Kind = 203
	Cobol85Kindlibraryattributefunction Cobol85Kind = 204
	Cobol85Kindlibraryattributeparameter Cobol85Kind = 205
	Cobol85Kindlibraryattributetitle Cobol85Kind = 206
	Cobol85Kindlibraryentryprocedureclauseformat1 Cobol85Kind = 207
	Cobol85Kindlibraryentryprocedureclauseformat2 Cobol85Kind = 208
	Cobol85Kindlibraryentryprocedureforclause Cobol85Kind = 209
	Cobol85Kindlibraryentryproceduregivingclause Cobol85Kind = 210
	Cobol85Kindlibraryentryprocedureusingclause Cobol85Kind = 211
	Cobol85Kindlibraryentryprocedureusingname Cobol85Kind = 212
	Cobol85Kindlibraryentryprocedurewithclause Cobol85Kind = 213
	Cobol85Kindlibraryentryprocedurewithname Cobol85Kind = 214
	Cobol85Kindlibraryiscommonclause Cobol85Kind = 215
	Cobol85Kindlibraryisglobalclause Cobol85Kind = 216
	Cobol85Kinddatadescriptionentry Cobol85Kind = 217
	Cobol85Kinddatadescriptionentryformat1 Cobol85Kind = 218
	Cobol85Kinddatadescriptionentryformat2 Cobol85Kind = 219
	Cobol85Kinddatadescriptionentryformat3 Cobol85Kind = 220
	Cobol85Kinddatadescriptionentryexecsql Cobol85Kind = 221
	Cobol85Kinddataalignedclause Cobol85Kind = 222
	Cobol85Kinddatablankwhenzeroclause Cobol85Kind = 223
	Cobol85Kinddatacommonownlocalclause Cobol85Kind = 224
	Cobol85Kinddataexternalclause Cobol85Kind = 225
	Cobol85Kinddataglobalclause Cobol85Kind = 226
	Cobol85Kinddataintegerstringclause Cobol85Kind = 227
	Cobol85Kinddatajustifiedclause Cobol85Kind = 228
	Cobol85Kinddataoccursclause Cobol85Kind = 229
	Cobol85Kinddataoccursto Cobol85Kind = 230
	Cobol85Kinddataoccurssort Cobol85Kind = 231
	Cobol85Kinddatapictureclause Cobol85Kind = 232
	Cobol85Kindpicturestring Cobol85Kind = 233
	Cobol85Kindpicturechars Cobol85Kind = 234
	Cobol85Kindpicturecardinality Cobol85Kind = 235
	Cobol85Kinddatareceivedbyclause Cobol85Kind = 236
	Cobol85Kinddatarecordareaclause Cobol85Kind = 237
	Cobol85Kinddataredefinesclause Cobol85Kind = 238
	Cobol85Kinddatarenamesclause Cobol85Kind = 239
	Cobol85Kinddatasignclause Cobol85Kind = 240
	Cobol85Kinddatasynchronizedclause Cobol85Kind = 241
	Cobol85Kinddatathreadlocalclause Cobol85Kind = 242
	Cobol85Kinddatatypeclause Cobol85Kind = 243
	Cobol85Kinddatatypedefclause Cobol85Kind = 244
	Cobol85Kinddatausageclause Cobol85Kind = 245
	Cobol85Kinddatausingclause Cobol85Kind = 246
	Cobol85Kinddatavalueclause Cobol85Kind = 247
	Cobol85Kinddatavalueinterval Cobol85Kind = 248
	Cobol85Kinddatavalueintervalfrom Cobol85Kind = 249
	Cobol85Kinddatavalueintervalto Cobol85Kind = 250
	Cobol85Kinddatawithlowerboundsclause Cobol85Kind = 251
	Cobol85Kindproceduredivision Cobol85Kind = 252
	Cobol85Kindproceduredivisionusingclause Cobol85Kind = 253
	Cobol85Kindproceduredivisiongivingclause Cobol85Kind = 254
	Cobol85Kindproceduredivisionusingparameter Cobol85Kind = 255
	Cobol85Kindproceduredivisionbyreferencephrase Cobol85Kind = 256
	Cobol85Kindproceduredivisionbyreference Cobol85Kind = 257
	Cobol85Kindproceduredivisionbyvaluephrase Cobol85Kind = 258
	Cobol85Kindproceduredivisionbyvalue Cobol85Kind = 259
	Cobol85Kindproceduredeclaratives Cobol85Kind = 260
	Cobol85Kindproceduredeclarative Cobol85Kind = 261
	Cobol85Kindproceduresectionheader Cobol85Kind = 262
	Cobol85Kindproceduredivisionbody Cobol85Kind = 263
	Cobol85Kindproceduresection Cobol85Kind = 264
	Cobol85Kindparagraphs Cobol85Kind = 265
	Cobol85Kindparagraph Cobol85Kind = 266
	Cobol85Kindsentence Cobol85Kind = 267
	Cobol85Kindstatement Cobol85Kind = 268
	Cobol85Kindacceptstatement Cobol85Kind = 269
	Cobol85Kindacceptfromdatestatement Cobol85Kind = 270
	Cobol85Kindacceptfrommnemonicstatement Cobol85Kind = 271
	Cobol85Kindacceptfromescapekeystatement Cobol85Kind = 272
	Cobol85Kindacceptmessagecountstatement Cobol85Kind = 273
	Cobol85Kindaddstatement Cobol85Kind = 274
	Cobol85Kindaddtostatement Cobol85Kind = 275
	Cobol85Kindaddtogivingstatement Cobol85Kind = 276
	Cobol85Kindaddcorrespondingstatement Cobol85Kind = 277
	Cobol85Kindaddfrom Cobol85Kind = 278
	Cobol85Kindaddto Cobol85Kind = 279
	Cobol85Kindaddtogiving Cobol85Kind = 280
	Cobol85Kindaddgiving Cobol85Kind = 281
	Cobol85Kindalteredgoto Cobol85Kind = 282
	Cobol85Kindalterstatement Cobol85Kind = 283
	Cobol85Kindalterproceedto Cobol85Kind = 284
	Cobol85Kindcallstatement Cobol85Kind = 285
	Cobol85Kindcallusingphrase Cobol85Kind = 286
	Cobol85Kindcallusingparameter Cobol85Kind = 287
	Cobol85Kindcallbyreferencephrase Cobol85Kind = 288
	Cobol85Kindcallbyreference Cobol85Kind = 289
	Cobol85Kindcallbyvaluephrase Cobol85Kind = 290
	Cobol85Kindcallbyvalue Cobol85Kind = 291
	Cobol85Kindcallbycontentphrase Cobol85Kind = 292
	Cobol85Kindcallbycontent Cobol85Kind = 293
	Cobol85Kindcallgivingphrase Cobol85Kind = 294
	Cobol85Kindcancelstatement Cobol85Kind = 295
	Cobol85Kindcancelcall Cobol85Kind = 296
	Cobol85Kindclosestatement Cobol85Kind = 297
	Cobol85Kindclosefile Cobol85Kind = 298
	Cobol85Kindclosereelunitstatement Cobol85Kind = 299
	Cobol85Kindcloserelativestatement Cobol85Kind = 300
	Cobol85Kindcloseportfileiostatement Cobol85Kind = 301
	Cobol85Kindcloseportfileiousing Cobol85Kind = 302
	Cobol85Kindcloseportfileiousingclosedisposition Cobol85Kind = 303
	Cobol85Kindcloseportfileiousingassociateddata Cobol85Kind = 304
	Cobol85Kindcloseportfileiousingassociateddatalength Cobol85Kind = 305
	Cobol85Kindcomputestatement Cobol85Kind = 306
	Cobol85Kindcomputestore Cobol85Kind = 307
	Cobol85Kindcontinuestatement Cobol85Kind = 308
	Cobol85Kinddeletestatement Cobol85Kind = 309
	Cobol85Kinddisablestatement Cobol85Kind = 310
	Cobol85Kinddisplaystatement Cobol85Kind = 311
	Cobol85Kinddisplayoperand Cobol85Kind = 312
	Cobol85Kinddisplayat Cobol85Kind = 313
	Cobol85Kinddisplayupon Cobol85Kind = 314
	Cobol85Kinddisplaywith Cobol85Kind = 315
	Cobol85Kinddividestatement Cobol85Kind = 316
	Cobol85Kinddivideintostatement Cobol85Kind = 317
	Cobol85Kinddivideintogivingstatement Cobol85Kind = 318
	Cobol85Kinddividebygivingstatement Cobol85Kind = 319
	Cobol85Kinddividegivingphrase Cobol85Kind = 320
	Cobol85Kinddivideinto Cobol85Kind = 321
	Cobol85Kinddividegiving Cobol85Kind = 322
	Cobol85Kinddivideremainder Cobol85Kind = 323
	Cobol85Kindenablestatement Cobol85Kind = 324
	Cobol85Kindentrystatement Cobol85Kind = 325
	Cobol85Kindevaluatestatement Cobol85Kind = 326
	Cobol85Kindevaluateselect Cobol85Kind = 327
	Cobol85Kindevaluatealsoselect Cobol85Kind = 328
	Cobol85Kindevaluatewhenphrase Cobol85Kind = 329
	Cobol85Kindevaluatewhen Cobol85Kind = 330
	Cobol85Kindevaluatecondition Cobol85Kind = 331
	Cobol85Kindevaluatethrough Cobol85Kind = 332
	Cobol85Kindevaluatealsocondition Cobol85Kind = 333
	Cobol85Kindevaluatewhenother Cobol85Kind = 334
	Cobol85Kindevaluatevalue Cobol85Kind = 335
	Cobol85Kindexeccicsstatement Cobol85Kind = 336
	Cobol85Kindexecsqlstatement Cobol85Kind = 337
	Cobol85Kindexecsqlimsstatement Cobol85Kind = 338
	Cobol85Kindexhibitstatement Cobol85Kind = 339
	Cobol85Kindexhibitoperand Cobol85Kind = 340
	Cobol85Kindexitstatement Cobol85Kind = 341
	Cobol85Kindgeneratestatement Cobol85Kind = 342
	Cobol85Kindgobackstatement Cobol85Kind = 343
	Cobol85Kindgotostatement Cobol85Kind = 344
	Cobol85Kindgotostatementsimple Cobol85Kind = 345
	Cobol85Kindgotodependingonstatement Cobol85Kind = 346
	Cobol85Kindifstatement Cobol85Kind = 347
	Cobol85Kindifthen Cobol85Kind = 348
	Cobol85Kindifelse Cobol85Kind = 349
	Cobol85Kindinitializestatement Cobol85Kind = 350
	Cobol85Kindinitializereplacingphrase Cobol85Kind = 351
	Cobol85Kindinitializereplacingby Cobol85Kind = 352
	Cobol85Kindinitiatestatement Cobol85Kind = 353
	Cobol85Kindinspectstatement Cobol85Kind = 354
	Cobol85Kindinspecttallyingphrase Cobol85Kind = 355
	Cobol85Kindinspectreplacingphrase Cobol85Kind = 356
	Cobol85Kindinspecttallyingreplacingphrase Cobol85Kind = 357
	Cobol85Kindinspectconvertingphrase Cobol85Kind = 358
	Cobol85Kindinspectfor Cobol85Kind = 359
	Cobol85Kindinspectcharacters Cobol85Kind = 360
	Cobol85Kindinspectreplacingcharacters Cobol85Kind = 361
	Cobol85Kindinspectallleadings Cobol85Kind = 362
	Cobol85Kindinspectreplacingallleadings Cobol85Kind = 363
	Cobol85Kindinspectallleading Cobol85Kind = 364
	Cobol85Kindinspectreplacingallleading Cobol85Kind = 365
	Cobol85Kindinspectby Cobol85Kind = 366
	Cobol85Kindinspectto Cobol85Kind = 367
	Cobol85Kindinspectbeforeafter Cobol85Kind = 368
	Cobol85Kindmergestatement Cobol85Kind = 369
	Cobol85Kindmergeonkeyclause Cobol85Kind = 370
	Cobol85Kindmergecollatingsequencephrase Cobol85Kind = 371
	Cobol85Kindmergecollatingalphanumeric Cobol85Kind = 372
	Cobol85Kindmergecollatingnational Cobol85Kind = 373
	Cobol85Kindmergeusing Cobol85Kind = 374
	Cobol85Kindmergeoutputprocedurephrase Cobol85Kind = 375
	Cobol85Kindmergeoutputthrough Cobol85Kind = 376
	Cobol85Kindmergegivingphrase Cobol85Kind = 377
	Cobol85Kindmergegiving Cobol85Kind = 378
	Cobol85Kindmovestatement Cobol85Kind = 379
	Cobol85Kindmovetostatement Cobol85Kind = 380
	Cobol85Kindmovetosendingarea Cobol85Kind = 381
	Cobol85Kindmovecorrespondingtostatement Cobol85Kind = 382
	Cobol85Kindmovecorrespondingtosendingarea Cobol85Kind = 383
	Cobol85Kindmultiplystatement Cobol85Kind = 384
	Cobol85Kindmultiplyregular Cobol85Kind = 385
	Cobol85Kindmultiplyregularoperand Cobol85Kind = 386
	Cobol85Kindmultiplygiving Cobol85Kind = 387
	Cobol85Kindmultiplygivingoperand Cobol85Kind = 388
	Cobol85Kindmultiplygivingresult Cobol85Kind = 389
	Cobol85Kindopenstatement Cobol85Kind = 390
	Cobol85Kindopeninputstatement Cobol85Kind = 391
	Cobol85Kindopeninput Cobol85Kind = 392
	Cobol85Kindopenoutputstatement Cobol85Kind = 393
	Cobol85Kindopenoutput Cobol85Kind = 394
	Cobol85Kindopeniostatement Cobol85Kind = 395
	Cobol85Kindopenextendstatement Cobol85Kind = 396
	Cobol85Kindperformstatement Cobol85Kind = 397
	Cobol85Kindperforminlinestatement Cobol85Kind = 398
	Cobol85Kindperformprocedurestatement Cobol85Kind = 399
	Cobol85Kindperformtype Cobol85Kind = 400
	Cobol85Kindperformtimes Cobol85Kind = 401
	Cobol85Kindperformuntil Cobol85Kind = 402
	Cobol85Kindperformvarying Cobol85Kind = 403
	Cobol85Kindperformvaryingclause Cobol85Kind = 404
	Cobol85Kindperformvaryingphrase Cobol85Kind = 405
	Cobol85Kindperformafter Cobol85Kind = 406
	Cobol85Kindperformfrom Cobol85Kind = 407
	Cobol85Kindperformby Cobol85Kind = 408
	Cobol85Kindperformtestclause Cobol85Kind = 409
	Cobol85Kindpurgestatement Cobol85Kind = 410
	Cobol85Kindreadstatement Cobol85Kind = 411
	Cobol85Kindreadinto Cobol85Kind = 412
	Cobol85Kindreadwith Cobol85Kind = 413
	Cobol85Kindreadkey Cobol85Kind = 414
	Cobol85Kindreceivestatement Cobol85Kind = 415
	Cobol85Kindreceivefromstatement Cobol85Kind = 416
	Cobol85Kindreceivefrom Cobol85Kind = 417
	Cobol85Kindreceiveintostatement Cobol85Kind = 418
	Cobol85Kindreceivenodata Cobol85Kind = 419
	Cobol85Kindreceivewithdata Cobol85Kind = 420
	Cobol85Kindreceivebefore Cobol85Kind = 421
	Cobol85Kindreceivewith Cobol85Kind = 422
	Cobol85Kindreceivethread Cobol85Kind = 423
	Cobol85Kindreceivesize Cobol85Kind = 424
	Cobol85Kindreceivestatus Cobol85Kind = 425
	Cobol85Kindreleasestatement Cobol85Kind = 426
	Cobol85Kindreturnstatement Cobol85Kind = 427
	Cobol85Kindreturninto Cobol85Kind = 428
	Cobol85Kindrewritestatement Cobol85Kind = 429
	Cobol85Kindrewritefrom Cobol85Kind = 430
	Cobol85Kindsearchstatement Cobol85Kind = 431
	Cobol85Kindsearchvarying Cobol85Kind = 432
	Cobol85Kindsearchwhen Cobol85Kind = 433
	Cobol85Kindsendstatement Cobol85Kind = 434
	Cobol85Kindsendstatementsync Cobol85Kind = 435
	Cobol85Kindsendstatementasync Cobol85Kind = 436
	Cobol85Kindsendfromphrase Cobol85Kind = 437
	Cobol85Kindsendwithphrase Cobol85Kind = 438
	Cobol85Kindsendreplacingphrase Cobol85Kind = 439
	Cobol85Kindsendadvancingphrase Cobol85Kind = 440
	Cobol85Kindsendadvancingpage Cobol85Kind = 441
	Cobol85Kindsendadvancinglines Cobol85Kind = 442
	Cobol85Kindsendadvancingmnemonic Cobol85Kind = 443
	Cobol85Kindsetstatement Cobol85Kind = 444
	Cobol85Kindsettostatement Cobol85Kind = 445
	Cobol85Kindsetupdownbystatement Cobol85Kind = 446
	Cobol85Kindsetto Cobol85Kind = 447
	Cobol85Kindsettovalue Cobol85Kind = 448
	Cobol85Kindsetbyvalue Cobol85Kind = 449
	Cobol85Kindsortstatement Cobol85Kind = 450
	Cobol85Kindsortonkeyclause Cobol85Kind = 451
	Cobol85Kindsortduplicatesphrase Cobol85Kind = 452
	Cobol85Kindsortcollatingsequencephrase Cobol85Kind = 453
	Cobol85Kindsortcollatingalphanumeric Cobol85Kind = 454
	Cobol85Kindsortcollatingnational Cobol85Kind = 455
	Cobol85Kindsortinputprocedurephrase Cobol85Kind = 456
	Cobol85Kindsortinputthrough Cobol85Kind = 457
	Cobol85Kindsortusing Cobol85Kind = 458
	Cobol85Kindsortoutputprocedurephrase Cobol85Kind = 459
	Cobol85Kindsortoutputthrough Cobol85Kind = 460
	Cobol85Kindsortgivingphrase Cobol85Kind = 461
	Cobol85Kindsortgiving Cobol85Kind = 462
	Cobol85Kindstartstatement Cobol85Kind = 463
	Cobol85Kindstartkey Cobol85Kind = 464
	Cobol85Kindstopstatement Cobol85Kind = 465
	Cobol85Kindstringstatement Cobol85Kind = 466
	Cobol85Kindstringsendingphrase Cobol85Kind = 467
	Cobol85Kindstringsending Cobol85Kind = 468
	Cobol85Kindstringdelimitedbyphrase Cobol85Kind = 469
	Cobol85Kindstringforphrase Cobol85Kind = 470
	Cobol85Kindstringintophrase Cobol85Kind = 471
	Cobol85Kindstringwithpointerphrase Cobol85Kind = 472
	Cobol85Kindsubtractstatement Cobol85Kind = 473
	Cobol85Kindsubtractfromstatement Cobol85Kind = 474
	Cobol85Kindsubtractfromgivingstatement Cobol85Kind = 475
	Cobol85Kindsubtractcorrespondingstatement Cobol85Kind = 476
	Cobol85Kindsubtractsubtrahend Cobol85Kind = 477
	Cobol85Kindsubtractminuend Cobol85Kind = 478
	Cobol85Kindsubtractminuendgiving Cobol85Kind = 479
	Cobol85Kindsubtractgiving Cobol85Kind = 480
	Cobol85Kindsubtractminuendcorresponding Cobol85Kind = 481
	Cobol85Kindterminatestatement Cobol85Kind = 482
	Cobol85Kindunstringstatement Cobol85Kind = 483
	Cobol85Kindunstringsendingphrase Cobol85Kind = 484
	Cobol85Kindunstringdelimitedbyphrase Cobol85Kind = 485
	Cobol85Kindunstringorallphrase Cobol85Kind = 486
	Cobol85Kindunstringintophrase Cobol85Kind = 487
	Cobol85Kindunstringinto Cobol85Kind = 488
	Cobol85Kindunstringdelimiterin Cobol85Kind = 489
	Cobol85Kindunstringcountin Cobol85Kind = 490
	Cobol85Kindunstringwithpointerphrase Cobol85Kind = 491
	Cobol85Kindunstringtallyingphrase Cobol85Kind = 492
	Cobol85Kindusestatement Cobol85Kind = 493
	Cobol85Kinduseafterclause Cobol85Kind = 494
	Cobol85Kinduseafteron Cobol85Kind = 495
	Cobol85Kindusedebugclause Cobol85Kind = 496
	Cobol85Kindusedebugon Cobol85Kind = 497
	Cobol85Kindwritestatement Cobol85Kind = 498
	Cobol85Kindwritefromphrase Cobol85Kind = 499
	Cobol85Kindwriteadvancingphrase Cobol85Kind = 500
	Cobol85Kindwriteadvancingpage Cobol85Kind = 501
	Cobol85Kindwriteadvancinglines Cobol85Kind = 502
	Cobol85Kindwriteadvancingmnemonic Cobol85Kind = 503
	Cobol85Kindwriteatendofpagephrase Cobol85Kind = 504
	Cobol85Kindwritenotatendofpagephrase Cobol85Kind = 505
	Cobol85Kindatendphrase Cobol85Kind = 506
	Cobol85Kindnotatendphrase Cobol85Kind = 507
	Cobol85Kindinvalidkeyphrase Cobol85Kind = 508
	Cobol85Kindnotinvalidkeyphrase Cobol85Kind = 509
	Cobol85Kindonoverflowphrase Cobol85Kind = 510
	Cobol85Kindnotonoverflowphrase Cobol85Kind = 511
	Cobol85Kindonsizeerrorphrase Cobol85Kind = 512
	Cobol85Kindnotonsizeerrorphrase Cobol85Kind = 513
	Cobol85Kindonexceptionclause Cobol85Kind = 514
	Cobol85Kindnotonexceptionclause Cobol85Kind = 515
	Cobol85Kindarithmeticexpression Cobol85Kind = 516
	Cobol85Kindplusminus Cobol85Kind = 517
	Cobol85Kindmultdivs Cobol85Kind = 518
	Cobol85Kindmultdiv Cobol85Kind = 519
	Cobol85Kindpowers Cobol85Kind = 520
	Cobol85Kindpower Cobol85Kind = 521
	Cobol85Kindbasis Cobol85Kind = 522
	Cobol85Kindcondition Cobol85Kind = 523
	Cobol85Kindandorcondition Cobol85Kind = 524
	Cobol85Kindcombinablecondition Cobol85Kind = 525
	Cobol85Kindsimplecondition Cobol85Kind = 526
	Cobol85Kindclasscondition Cobol85Kind = 527
	Cobol85Kindconditionnamereference Cobol85Kind = 528
	Cobol85Kindconditionnamesubscriptreference Cobol85Kind = 529
	Cobol85Kindrelationcondition Cobol85Kind = 530
	Cobol85Kindrelationsigncondition Cobol85Kind = 531
	Cobol85Kindrelationarithmeticcomparison Cobol85Kind = 532
	Cobol85Kindrelationcombinedcomparison Cobol85Kind = 533
	Cobol85Kindrelationcombinedcondition Cobol85Kind = 534
	Cobol85Kindrelationaloperator Cobol85Kind = 535
	Cobol85Kindabbreviation Cobol85Kind = 536
	Cobol85Kindidentifier Cobol85Kind = 537
	Cobol85Kindtablecall Cobol85Kind = 538
	Cobol85Kindfunctioncall Cobol85Kind = 539
	Cobol85Kindreferencemodifier Cobol85Kind = 540
	Cobol85Kindcharacterposition Cobol85Kind = 541
	Cobol85Kindlength Cobol85Kind = 542
	Cobol85Kindsubscript Cobol85Kind = 543
	Cobol85Kindargument Cobol85Kind = 544
	Cobol85Kindqualifieddataname Cobol85Kind = 545
	Cobol85Kindqualifieddatanameformat1 Cobol85Kind = 546
	Cobol85Kindqualifieddatanameformat2 Cobol85Kind = 547
	Cobol85Kindqualifieddatanameformat3 Cobol85Kind = 548
	Cobol85Kindqualifieddatanameformat4 Cobol85Kind = 549
	Cobol85Kindqualifiedindata Cobol85Kind = 550
	Cobol85Kindindata Cobol85Kind = 551
	Cobol85Kindinfile Cobol85Kind = 552
	Cobol85Kindinmnemonic Cobol85Kind = 553
	Cobol85Kindinsection Cobol85Kind = 554
	Cobol85Kindinlibrary Cobol85Kind = 555
	Cobol85Kindintable Cobol85Kind = 556
	Cobol85Kindalphabetname Cobol85Kind = 557
	Cobol85Kindassignmentname Cobol85Kind = 558
	Cobol85Kindbasisname Cobol85Kind = 559
	Cobol85Kindcdname Cobol85Kind = 560
	Cobol85Kindclassname Cobol85Kind = 561
	Cobol85Kindcomputername Cobol85Kind = 562
	Cobol85Kindconditionname Cobol85Kind = 563
	Cobol85Kinddataname Cobol85Kind = 564
	Cobol85Kinddatadescname Cobol85Kind = 565
	Cobol85Kindenvironmentname Cobol85Kind = 566
	Cobol85Kindfilename Cobol85Kind = 567
	Cobol85Kindfunctionname Cobol85Kind = 568
	Cobol85Kindindexname Cobol85Kind = 569
	Cobol85Kindlanguagename Cobol85Kind = 570
	Cobol85Kindlibraryname Cobol85Kind = 571
	Cobol85Kindlocalname Cobol85Kind = 572
	Cobol85Kindmnemonicname Cobol85Kind = 573
	Cobol85Kindparagraphname Cobol85Kind = 574
	Cobol85Kindprocedurename Cobol85Kind = 575
	Cobol85Kindprogramname Cobol85Kind = 576
	Cobol85Kindrecordname Cobol85Kind = 577
	Cobol85Kindreportname Cobol85Kind = 578
	Cobol85Kindroutinename Cobol85Kind = 579
	Cobol85Kindscreenname Cobol85Kind = 580
	Cobol85Kindsectionname Cobol85Kind = 581
	Cobol85Kindsystemname Cobol85Kind = 582
	Cobol85Kindsymboliccharacter Cobol85Kind = 583
	Cobol85Kindtextname Cobol85Kind = 584
	Cobol85Kindcobolword Cobol85Kind = 585
	Cobol85Kindliteral Cobol85Kind = 586
	Cobol85Kindbooleanliteral Cobol85Kind = 587
	Cobol85Kindnumericliteral Cobol85Kind = 588
	Cobol85Kindintegerliteral Cobol85Kind = 589
	Cobol85Kindcicsdfhrespliteral Cobol85Kind = 590
	Cobol85Kindcicsdfhvalueliteral Cobol85Kind = 591
	Cobol85Kindfigurativeconstant Cobol85Kind = 592
	Cobol85Kindspecialregister Cobol85Kind = 593
	Cobol85Kindcommententry Cobol85Kind = 594
)

var EnumNamesCobol85Kind = map[Cobol85Kind]string{
	Cobol85Kindstartrule:"startrule",
	Cobol85Kindcompilationunit:"compilationunit",
	Cobol85Kindprogramunit:"programunit",
	Cobol85Kindendprogramstatement:"endprogramstatement",
	Cobol85Kindidentificationdivision:"identificationdivision",
	Cobol85Kindidentificationdivisionbody:"identificationdivisionbody",
	Cobol85Kindprogramidparagraph:"programidparagraph",
	Cobol85Kindauthorparagraph:"authorparagraph",
	Cobol85Kindinstallationparagraph:"installationparagraph",
	Cobol85Kinddatewrittenparagraph:"datewrittenparagraph",
	Cobol85Kinddatecompiledparagraph:"datecompiledparagraph",
	Cobol85Kindsecurityparagraph:"securityparagraph",
	Cobol85Kindremarksparagraph:"remarksparagraph",
	Cobol85Kindenvironmentdivision:"environmentdivision",
	Cobol85Kindenvironmentdivisionbody:"environmentdivisionbody",
	Cobol85Kindconfigurationsection:"configurationsection",
	Cobol85Kindconfigurationsectionparagraph:"configurationsectionparagraph",
	Cobol85Kindsourcecomputerparagraph:"sourcecomputerparagraph",
	Cobol85Kindobjectcomputerparagraph:"objectcomputerparagraph",
	Cobol85Kindobjectcomputerclause:"objectcomputerclause",
	Cobol85Kindmemorysizeclause:"memorysizeclause",
	Cobol85Kinddisksizeclause:"disksizeclause",
	Cobol85Kindcollatingsequenceclause:"collatingsequenceclause",
	Cobol85Kindcollatingsequenceclausealphanumeric:"collatingsequenceclausealphanumeric",
	Cobol85Kindcollatingsequenceclausenational:"collatingsequenceclausenational",
	Cobol85Kindsegmentlimitclause:"segmentlimitclause",
	Cobol85Kindcharactersetclause:"charactersetclause",
	Cobol85Kindspecialnamesparagraph:"specialnamesparagraph",
	Cobol85Kindspecialnameclause:"specialnameclause",
	Cobol85Kindalphabetclause:"alphabetclause",
	Cobol85Kindalphabetclauseformat1:"alphabetclauseformat1",
	Cobol85Kindalphabetliterals:"alphabetliterals",
	Cobol85Kindalphabetthrough:"alphabetthrough",
	Cobol85Kindalphabetalso:"alphabetalso",
	Cobol85Kindalphabetclauseformat2:"alphabetclauseformat2",
	Cobol85Kindchannelclause:"channelclause",
	Cobol85Kindclassclause:"classclause",
	Cobol85Kindclassclausethrough:"classclausethrough",
	Cobol85Kindclassclausefrom:"classclausefrom",
	Cobol85Kindclassclauseto:"classclauseto",
	Cobol85Kindcurrencysignclause:"currencysignclause",
	Cobol85Kinddecimalpointclause:"decimalpointclause",
	Cobol85Kinddefaultcomputationalsignclause:"defaultcomputationalsignclause",
	Cobol85Kinddefaultdisplaysignclause:"defaultdisplaysignclause",
	Cobol85Kindenvironmentswitchnameclause:"environmentswitchnameclause",
	Cobol85Kindenvironmentswitchnamespecialnamesstatusphrase:"environmentswitchnamespecialnamesstatusphrase",
	Cobol85Kindodtclause:"odtclause",
	Cobol85Kindreservenetworkclause:"reservenetworkclause",
	Cobol85Kindsymboliccharactersclause:"symboliccharactersclause",
	Cobol85Kindsymboliccharacters:"symboliccharacters",
	Cobol85Kindinputoutputsection:"inputoutputsection",
	Cobol85Kindinputoutputsectionparagraph:"inputoutputsectionparagraph",
	Cobol85Kindfilecontrolparagraph:"filecontrolparagraph",
	Cobol85Kindfilecontrolentry:"filecontrolentry",
	Cobol85Kindselectclause:"selectclause",
	Cobol85Kindfilecontrolclause:"filecontrolclause",
	Cobol85Kindassignclause:"assignclause",
	Cobol85Kindreserveclause:"reserveclause",
	Cobol85Kindorganizationclause:"organizationclause",
	Cobol85Kindpaddingcharacterclause:"paddingcharacterclause",
	Cobol85Kindrecorddelimiterclause:"recorddelimiterclause",
	Cobol85Kindaccessmodeclause:"accessmodeclause",
	Cobol85Kindrecordkeyclause:"recordkeyclause",
	Cobol85Kindalternaterecordkeyclause:"alternaterecordkeyclause",
	Cobol85Kindpasswordclause:"passwordclause",
	Cobol85Kindfilestatusclause:"filestatusclause",
	Cobol85Kindrelativekeyclause:"relativekeyclause",
	Cobol85Kindiocontrolparagraph:"iocontrolparagraph",
	Cobol85Kindiocontrolclause:"iocontrolclause",
	Cobol85Kindrerunclause:"rerunclause",
	Cobol85Kindreruneveryrecords:"reruneveryrecords",
	Cobol85Kindreruneveryof:"reruneveryof",
	Cobol85Kindreruneveryclock:"reruneveryclock",
	Cobol85Kindsameclause:"sameclause",
	Cobol85Kindmultiplefileclause:"multiplefileclause",
	Cobol85Kindmultiplefileposition:"multiplefileposition",
	Cobol85Kindcommitmentcontrolclause:"commitmentcontrolclause",
	Cobol85Kinddatadivision:"datadivision",
	Cobol85Kinddatadivisionsection:"datadivisionsection",
	Cobol85Kindfilesection:"filesection",
	Cobol85Kindfiledescriptionentry:"filedescriptionentry",
	Cobol85Kindfiledescriptionentryclause:"filedescriptionentryclause",
	Cobol85Kindexternalclause:"externalclause",
	Cobol85Kindglobalclause:"globalclause",
	Cobol85Kindblockcontainsclause:"blockcontainsclause",
	Cobol85Kindblockcontainsto:"blockcontainsto",
	Cobol85Kindrecordcontainsclause:"recordcontainsclause",
	Cobol85Kindrecordcontainsclauseformat1:"recordcontainsclauseformat1",
	Cobol85Kindrecordcontainsclauseformat2:"recordcontainsclauseformat2",
	Cobol85Kindrecordcontainsclauseformat3:"recordcontainsclauseformat3",
	Cobol85Kindrecordcontainsto:"recordcontainsto",
	Cobol85Kindlabelrecordsclause:"labelrecordsclause",
	Cobol85Kindvalueofclause:"valueofclause",
	Cobol85Kindvaluepair:"valuepair",
	Cobol85Kinddatarecordsclause:"datarecordsclause",
	Cobol85Kindlinageclause:"linageclause",
	Cobol85Kindlinageat:"linageat",
	Cobol85Kindlinagefootingat:"linagefootingat",
	Cobol85Kindlinagelinesattop:"linagelinesattop",
	Cobol85Kindlinagelinesatbottom:"linagelinesatbottom",
	Cobol85Kindrecordingmodeclause:"recordingmodeclause",
	Cobol85Kindmodestatement:"modestatement",
	Cobol85Kindcodesetclause:"codesetclause",
	Cobol85Kindreportclause:"reportclause",
	Cobol85Kinddatabasesection:"databasesection",
	Cobol85Kinddatabasesectionentry:"databasesectionentry",
	Cobol85Kindworkingstoragesection:"workingstoragesection",
	Cobol85Kindlinkagesection:"linkagesection",
	Cobol85Kindcommunicationsection:"communicationsection",
	Cobol85Kindcommunicationdescriptionentry:"communicationdescriptionentry",
	Cobol85Kindcommunicationdescriptionentryformat1:"communicationdescriptionentryformat1",
	Cobol85Kindcommunicationdescriptionentryformat2:"communicationdescriptionentryformat2",
	Cobol85Kindcommunicationdescriptionentryformat3:"communicationdescriptionentryformat3",
	Cobol85Kinddestinationcountclause:"destinationcountclause",
	Cobol85Kinddestinationtableclause:"destinationtableclause",
	Cobol85Kindendkeyclause:"endkeyclause",
	Cobol85Kinderrorkeyclause:"errorkeyclause",
	Cobol85Kindmessagecountclause:"messagecountclause",
	Cobol85Kindmessagedateclause:"messagedateclause",
	Cobol85Kindmessagetimeclause:"messagetimeclause",
	Cobol85Kindstatuskeyclause:"statuskeyclause",
	Cobol85Kindsymbolicdestinationclause:"symbolicdestinationclause",
	Cobol85Kindsymbolicqueueclause:"symbolicqueueclause",
	Cobol85Kindsymbolicsourceclause:"symbolicsourceclause",
	Cobol85Kindsymbolicterminalclause:"symbolicterminalclause",
	Cobol85Kindsymbolicsubqueueclause:"symbolicsubqueueclause",
	Cobol85Kindtextlengthclause:"textlengthclause",
	Cobol85Kindlocalstoragesection:"localstoragesection",
	Cobol85Kindscreensection:"screensection",
	Cobol85Kindscreendescriptionentry:"screendescriptionentry",
	Cobol85Kindscreendescriptionblankclause:"screendescriptionblankclause",
	Cobol85Kindscreendescriptionbellclause:"screendescriptionbellclause",
	Cobol85Kindscreendescriptionblinkclause:"screendescriptionblinkclause",
	Cobol85Kindscreendescriptioneraseclause:"screendescriptioneraseclause",
	Cobol85Kindscreendescriptionlightclause:"screendescriptionlightclause",
	Cobol85Kindscreendescriptiongridclause:"screendescriptiongridclause",
	Cobol85Kindscreendescriptionreversevideoclause:"screendescriptionreversevideoclause",
	Cobol85Kindscreendescriptionunderlineclause:"screendescriptionunderlineclause",
	Cobol85Kindscreendescriptionsizeclause:"screendescriptionsizeclause",
	Cobol85Kindscreendescriptionlineclause:"screendescriptionlineclause",
	Cobol85Kindscreendescriptioncolumnclause:"screendescriptioncolumnclause",
	Cobol85Kindscreendescriptionforegroundcolorclause:"screendescriptionforegroundcolorclause",
	Cobol85Kindscreendescriptionbackgroundcolorclause:"screendescriptionbackgroundcolorclause",
	Cobol85Kindscreendescriptioncontrolclause:"screendescriptioncontrolclause",
	Cobol85Kindscreendescriptionvalueclause:"screendescriptionvalueclause",
	Cobol85Kindscreendescriptionpictureclause:"screendescriptionpictureclause",
	Cobol85Kindscreendescriptionfromclause:"screendescriptionfromclause",
	Cobol85Kindscreendescriptiontoclause:"screendescriptiontoclause",
	Cobol85Kindscreendescriptionusingclause:"screendescriptionusingclause",
	Cobol85Kindscreendescriptionusageclause:"screendescriptionusageclause",
	Cobol85Kindscreendescriptionblankwhenzeroclause:"screendescriptionblankwhenzeroclause",
	Cobol85Kindscreendescriptionjustifiedclause:"screendescriptionjustifiedclause",
	Cobol85Kindscreendescriptionsignclause:"screendescriptionsignclause",
	Cobol85Kindscreendescriptionautoclause:"screendescriptionautoclause",
	Cobol85Kindscreendescriptionsecureclause:"screendescriptionsecureclause",
	Cobol85Kindscreendescriptionrequiredclause:"screendescriptionrequiredclause",
	Cobol85Kindscreendescriptionpromptclause:"screendescriptionpromptclause",
	Cobol85Kindscreendescriptionpromptoccursclause:"screendescriptionpromptoccursclause",
	Cobol85Kindscreendescriptionfullclause:"screendescriptionfullclause",
	Cobol85Kindscreendescriptionzerofillclause:"screendescriptionzerofillclause",
	Cobol85Kindreportsection:"reportsection",
	Cobol85Kindreportdescription:"reportdescription",
	Cobol85Kindreportdescriptionentry:"reportdescriptionentry",
	Cobol85Kindreportdescriptionglobalclause:"reportdescriptionglobalclause",
	Cobol85Kindreportdescriptionpagelimitclause:"reportdescriptionpagelimitclause",
	Cobol85Kindreportdescriptionheadingclause:"reportdescriptionheadingclause",
	Cobol85Kindreportdescriptionfirstdetailclause:"reportdescriptionfirstdetailclause",
	Cobol85Kindreportdescriptionlastdetailclause:"reportdescriptionlastdetailclause",
	Cobol85Kindreportdescriptionfootingclause:"reportdescriptionfootingclause",
	Cobol85Kindreportgroupdescriptionentry:"reportgroupdescriptionentry",
	Cobol85Kindreportgroupdescriptionentryformat1:"reportgroupdescriptionentryformat1",
	Cobol85Kindreportgroupdescriptionentryformat2:"reportgroupdescriptionentryformat2",
	Cobol85Kindreportgroupdescriptionentryformat3:"reportgroupdescriptionentryformat3",
	Cobol85Kindreportgroupblankwhenzeroclause:"reportgroupblankwhenzeroclause",
	Cobol85Kindreportgroupcolumnnumberclause:"reportgroupcolumnnumberclause",
	Cobol85Kindreportgroupindicateclause:"reportgroupindicateclause",
	Cobol85Kindreportgroupjustifiedclause:"reportgroupjustifiedclause",
	Cobol85Kindreportgrouplinenumberclause:"reportgrouplinenumberclause",
	Cobol85Kindreportgrouplinenumbernextpage:"reportgrouplinenumbernextpage",
	Cobol85Kindreportgrouplinenumberplus:"reportgrouplinenumberplus",
	Cobol85Kindreportgroupnextgroupclause:"reportgroupnextgroupclause",
	Cobol85Kindreportgroupnextgroupplus:"reportgroupnextgroupplus",
	Cobol85Kindreportgroupnextgroupnextpage:"reportgroupnextgroupnextpage",
	Cobol85Kindreportgrouppictureclause:"reportgrouppictureclause",
	Cobol85Kindreportgroupresetclause:"reportgroupresetclause",
	Cobol85Kindreportgroupsignclause:"reportgroupsignclause",
	Cobol85Kindreportgroupsourceclause:"reportgroupsourceclause",
	Cobol85Kindreportgroupsumclause:"reportgroupsumclause",
	Cobol85Kindreportgrouptypeclause:"reportgrouptypeclause",
	Cobol85Kindreportgrouptypereportheading:"reportgrouptypereportheading",
	Cobol85Kindreportgrouptypepageheading:"reportgrouptypepageheading",
	Cobol85Kindreportgrouptypecontrolheading:"reportgrouptypecontrolheading",
	Cobol85Kindreportgrouptypedetail:"reportgrouptypedetail",
	Cobol85Kindreportgrouptypecontrolfooting:"reportgrouptypecontrolfooting",
	Cobol85Kindreportgroupusageclause:"reportgroupusageclause",
	Cobol85Kindreportgrouptypepagefooting:"reportgrouptypepagefooting",
	Cobol85Kindreportgrouptypereportfooting:"reportgrouptypereportfooting",
	Cobol85Kindreportgroupvalueclause:"reportgroupvalueclause",
	Cobol85Kindprogramlibrarysection:"programlibrarysection",
	Cobol85Kindlibrarydescriptionentry:"librarydescriptionentry",
	Cobol85Kindlibrarydescriptionentryformat1:"librarydescriptionentryformat1",
	Cobol85Kindlibrarydescriptionentryformat2:"librarydescriptionentryformat2",
	Cobol85Kindlibraryattributeclauseformat1:"libraryattributeclauseformat1",
	Cobol85Kindlibraryattributeclauseformat2:"libraryattributeclauseformat2",
	Cobol85Kindlibraryattributefunction:"libraryattributefunction",
	Cobol85Kindlibraryattributeparameter:"libraryattributeparameter",
	Cobol85Kindlibraryattributetitle:"libraryattributetitle",
	Cobol85Kindlibraryentryprocedureclauseformat1:"libraryentryprocedureclauseformat1",
	Cobol85Kindlibraryentryprocedureclauseformat2:"libraryentryprocedureclauseformat2",
	Cobol85Kindlibraryentryprocedureforclause:"libraryentryprocedureforclause",
	Cobol85Kindlibraryentryproceduregivingclause:"libraryentryproceduregivingclause",
	Cobol85Kindlibraryentryprocedureusingclause:"libraryentryprocedureusingclause",
	Cobol85Kindlibraryentryprocedureusingname:"libraryentryprocedureusingname",
	Cobol85Kindlibraryentryprocedurewithclause:"libraryentryprocedurewithclause",
	Cobol85Kindlibraryentryprocedurewithname:"libraryentryprocedurewithname",
	Cobol85Kindlibraryiscommonclause:"libraryiscommonclause",
	Cobol85Kindlibraryisglobalclause:"libraryisglobalclause",
	Cobol85Kinddatadescriptionentry:"datadescriptionentry",
	Cobol85Kinddatadescriptionentryformat1:"datadescriptionentryformat1",
	Cobol85Kinddatadescriptionentryformat2:"datadescriptionentryformat2",
	Cobol85Kinddatadescriptionentryformat3:"datadescriptionentryformat3",
	Cobol85Kinddatadescriptionentryexecsql:"datadescriptionentryexecsql",
	Cobol85Kinddataalignedclause:"dataalignedclause",
	Cobol85Kinddatablankwhenzeroclause:"datablankwhenzeroclause",
	Cobol85Kinddatacommonownlocalclause:"datacommonownlocalclause",
	Cobol85Kinddataexternalclause:"dataexternalclause",
	Cobol85Kinddataglobalclause:"dataglobalclause",
	Cobol85Kinddataintegerstringclause:"dataintegerstringclause",
	Cobol85Kinddatajustifiedclause:"datajustifiedclause",
	Cobol85Kinddataoccursclause:"dataoccursclause",
	Cobol85Kinddataoccursto:"dataoccursto",
	Cobol85Kinddataoccurssort:"dataoccurssort",
	Cobol85Kinddatapictureclause:"datapictureclause",
	Cobol85Kindpicturestring:"picturestring",
	Cobol85Kindpicturechars:"picturechars",
	Cobol85Kindpicturecardinality:"picturecardinality",
	Cobol85Kinddatareceivedbyclause:"datareceivedbyclause",
	Cobol85Kinddatarecordareaclause:"datarecordareaclause",
	Cobol85Kinddataredefinesclause:"dataredefinesclause",
	Cobol85Kinddatarenamesclause:"datarenamesclause",
	Cobol85Kinddatasignclause:"datasignclause",
	Cobol85Kinddatasynchronizedclause:"datasynchronizedclause",
	Cobol85Kinddatathreadlocalclause:"datathreadlocalclause",
	Cobol85Kinddatatypeclause:"datatypeclause",
	Cobol85Kinddatatypedefclause:"datatypedefclause",
	Cobol85Kinddatausageclause:"datausageclause",
	Cobol85Kinddatausingclause:"datausingclause",
	Cobol85Kinddatavalueclause:"datavalueclause",
	Cobol85Kinddatavalueinterval:"datavalueinterval",
	Cobol85Kinddatavalueintervalfrom:"datavalueintervalfrom",
	Cobol85Kinddatavalueintervalto:"datavalueintervalto",
	Cobol85Kinddatawithlowerboundsclause:"datawithlowerboundsclause",
	Cobol85Kindproceduredivision:"proceduredivision",
	Cobol85Kindproceduredivisionusingclause:"proceduredivisionusingclause",
	Cobol85Kindproceduredivisiongivingclause:"proceduredivisiongivingclause",
	Cobol85Kindproceduredivisionusingparameter:"proceduredivisionusingparameter",
	Cobol85Kindproceduredivisionbyreferencephrase:"proceduredivisionbyreferencephrase",
	Cobol85Kindproceduredivisionbyreference:"proceduredivisionbyreference",
	Cobol85Kindproceduredivisionbyvaluephrase:"proceduredivisionbyvaluephrase",
	Cobol85Kindproceduredivisionbyvalue:"proceduredivisionbyvalue",
	Cobol85Kindproceduredeclaratives:"proceduredeclaratives",
	Cobol85Kindproceduredeclarative:"proceduredeclarative",
	Cobol85Kindproceduresectionheader:"proceduresectionheader",
	Cobol85Kindproceduredivisionbody:"proceduredivisionbody",
	Cobol85Kindproceduresection:"proceduresection",
	Cobol85Kindparagraphs:"paragraphs",
	Cobol85Kindparagraph:"paragraph",
	Cobol85Kindsentence:"sentence",
	Cobol85Kindstatement:"statement",
	Cobol85Kindacceptstatement:"acceptstatement",
	Cobol85Kindacceptfromdatestatement:"acceptfromdatestatement",
	Cobol85Kindacceptfrommnemonicstatement:"acceptfrommnemonicstatement",
	Cobol85Kindacceptfromescapekeystatement:"acceptfromescapekeystatement",
	Cobol85Kindacceptmessagecountstatement:"acceptmessagecountstatement",
	Cobol85Kindaddstatement:"addstatement",
	Cobol85Kindaddtostatement:"addtostatement",
	Cobol85Kindaddtogivingstatement:"addtogivingstatement",
	Cobol85Kindaddcorrespondingstatement:"addcorrespondingstatement",
	Cobol85Kindaddfrom:"addfrom",
	Cobol85Kindaddto:"addto",
	Cobol85Kindaddtogiving:"addtogiving",
	Cobol85Kindaddgiving:"addgiving",
	Cobol85Kindalteredgoto:"alteredgoto",
	Cobol85Kindalterstatement:"alterstatement",
	Cobol85Kindalterproceedto:"alterproceedto",
	Cobol85Kindcallstatement:"callstatement",
	Cobol85Kindcallusingphrase:"callusingphrase",
	Cobol85Kindcallusingparameter:"callusingparameter",
	Cobol85Kindcallbyreferencephrase:"callbyreferencephrase",
	Cobol85Kindcallbyreference:"callbyreference",
	Cobol85Kindcallbyvaluephrase:"callbyvaluephrase",
	Cobol85Kindcallbyvalue:"callbyvalue",
	Cobol85Kindcallbycontentphrase:"callbycontentphrase",
	Cobol85Kindcallbycontent:"callbycontent",
	Cobol85Kindcallgivingphrase:"callgivingphrase",
	Cobol85Kindcancelstatement:"cancelstatement",
	Cobol85Kindcancelcall:"cancelcall",
	Cobol85Kindclosestatement:"closestatement",
	Cobol85Kindclosefile:"closefile",
	Cobol85Kindclosereelunitstatement:"closereelunitstatement",
	Cobol85Kindcloserelativestatement:"closerelativestatement",
	Cobol85Kindcloseportfileiostatement:"closeportfileiostatement",
	Cobol85Kindcloseportfileiousing:"closeportfileiousing",
	Cobol85Kindcloseportfileiousingclosedisposition:"closeportfileiousingclosedisposition",
	Cobol85Kindcloseportfileiousingassociateddata:"closeportfileiousingassociateddata",
	Cobol85Kindcloseportfileiousingassociateddatalength:"closeportfileiousingassociateddatalength",
	Cobol85Kindcomputestatement:"computestatement",
	Cobol85Kindcomputestore:"computestore",
	Cobol85Kindcontinuestatement:"continuestatement",
	Cobol85Kinddeletestatement:"deletestatement",
	Cobol85Kinddisablestatement:"disablestatement",
	Cobol85Kinddisplaystatement:"displaystatement",
	Cobol85Kinddisplayoperand:"displayoperand",
	Cobol85Kinddisplayat:"displayat",
	Cobol85Kinddisplayupon:"displayupon",
	Cobol85Kinddisplaywith:"displaywith",
	Cobol85Kinddividestatement:"dividestatement",
	Cobol85Kinddivideintostatement:"divideintostatement",
	Cobol85Kinddivideintogivingstatement:"divideintogivingstatement",
	Cobol85Kinddividebygivingstatement:"dividebygivingstatement",
	Cobol85Kinddividegivingphrase:"dividegivingphrase",
	Cobol85Kinddivideinto:"divideinto",
	Cobol85Kinddividegiving:"dividegiving",
	Cobol85Kinddivideremainder:"divideremainder",
	Cobol85Kindenablestatement:"enablestatement",
	Cobol85Kindentrystatement:"entrystatement",
	Cobol85Kindevaluatestatement:"evaluatestatement",
	Cobol85Kindevaluateselect:"evaluateselect",
	Cobol85Kindevaluatealsoselect:"evaluatealsoselect",
	Cobol85Kindevaluatewhenphrase:"evaluatewhenphrase",
	Cobol85Kindevaluatewhen:"evaluatewhen",
	Cobol85Kindevaluatecondition:"evaluatecondition",
	Cobol85Kindevaluatethrough:"evaluatethrough",
	Cobol85Kindevaluatealsocondition:"evaluatealsocondition",
	Cobol85Kindevaluatewhenother:"evaluatewhenother",
	Cobol85Kindevaluatevalue:"evaluatevalue",
	Cobol85Kindexeccicsstatement:"execcicsstatement",
	Cobol85Kindexecsqlstatement:"execsqlstatement",
	Cobol85Kindexecsqlimsstatement:"execsqlimsstatement",
	Cobol85Kindexhibitstatement:"exhibitstatement",
	Cobol85Kindexhibitoperand:"exhibitoperand",
	Cobol85Kindexitstatement:"exitstatement",
	Cobol85Kindgeneratestatement:"generatestatement",
	Cobol85Kindgobackstatement:"gobackstatement",
	Cobol85Kindgotostatement:"gotostatement",
	Cobol85Kindgotostatementsimple:"gotostatementsimple",
	Cobol85Kindgotodependingonstatement:"gotodependingonstatement",
	Cobol85Kindifstatement:"ifstatement",
	Cobol85Kindifthen:"ifthen",
	Cobol85Kindifelse:"ifelse",
	Cobol85Kindinitializestatement:"initializestatement",
	Cobol85Kindinitializereplacingphrase:"initializereplacingphrase",
	Cobol85Kindinitializereplacingby:"initializereplacingby",
	Cobol85Kindinitiatestatement:"initiatestatement",
	Cobol85Kindinspectstatement:"inspectstatement",
	Cobol85Kindinspecttallyingphrase:"inspecttallyingphrase",
	Cobol85Kindinspectreplacingphrase:"inspectreplacingphrase",
	Cobol85Kindinspecttallyingreplacingphrase:"inspecttallyingreplacingphrase",
	Cobol85Kindinspectconvertingphrase:"inspectconvertingphrase",
	Cobol85Kindinspectfor:"inspectfor",
	Cobol85Kindinspectcharacters:"inspectcharacters",
	Cobol85Kindinspectreplacingcharacters:"inspectreplacingcharacters",
	Cobol85Kindinspectallleadings:"inspectallleadings",
	Cobol85Kindinspectreplacingallleadings:"inspectreplacingallleadings",
	Cobol85Kindinspectallleading:"inspectallleading",
	Cobol85Kindinspectreplacingallleading:"inspectreplacingallleading",
	Cobol85Kindinspectby:"inspectby",
	Cobol85Kindinspectto:"inspectto",
	Cobol85Kindinspectbeforeafter:"inspectbeforeafter",
	Cobol85Kindmergestatement:"mergestatement",
	Cobol85Kindmergeonkeyclause:"mergeonkeyclause",
	Cobol85Kindmergecollatingsequencephrase:"mergecollatingsequencephrase",
	Cobol85Kindmergecollatingalphanumeric:"mergecollatingalphanumeric",
	Cobol85Kindmergecollatingnational:"mergecollatingnational",
	Cobol85Kindmergeusing:"mergeusing",
	Cobol85Kindmergeoutputprocedurephrase:"mergeoutputprocedurephrase",
	Cobol85Kindmergeoutputthrough:"mergeoutputthrough",
	Cobol85Kindmergegivingphrase:"mergegivingphrase",
	Cobol85Kindmergegiving:"mergegiving",
	Cobol85Kindmovestatement:"movestatement",
	Cobol85Kindmovetostatement:"movetostatement",
	Cobol85Kindmovetosendingarea:"movetosendingarea",
	Cobol85Kindmovecorrespondingtostatement:"movecorrespondingtostatement",
	Cobol85Kindmovecorrespondingtosendingarea:"movecorrespondingtosendingarea",
	Cobol85Kindmultiplystatement:"multiplystatement",
	Cobol85Kindmultiplyregular:"multiplyregular",
	Cobol85Kindmultiplyregularoperand:"multiplyregularoperand",
	Cobol85Kindmultiplygiving:"multiplygiving",
	Cobol85Kindmultiplygivingoperand:"multiplygivingoperand",
	Cobol85Kindmultiplygivingresult:"multiplygivingresult",
	Cobol85Kindopenstatement:"openstatement",
	Cobol85Kindopeninputstatement:"openinputstatement",
	Cobol85Kindopeninput:"openinput",
	Cobol85Kindopenoutputstatement:"openoutputstatement",
	Cobol85Kindopenoutput:"openoutput",
	Cobol85Kindopeniostatement:"openiostatement",
	Cobol85Kindopenextendstatement:"openextendstatement",
	Cobol85Kindperformstatement:"performstatement",
	Cobol85Kindperforminlinestatement:"performinlinestatement",
	Cobol85Kindperformprocedurestatement:"performprocedurestatement",
	Cobol85Kindperformtype:"performtype",
	Cobol85Kindperformtimes:"performtimes",
	Cobol85Kindperformuntil:"performuntil",
	Cobol85Kindperformvarying:"performvarying",
	Cobol85Kindperformvaryingclause:"performvaryingclause",
	Cobol85Kindperformvaryingphrase:"performvaryingphrase",
	Cobol85Kindperformafter:"performafter",
	Cobol85Kindperformfrom:"performfrom",
	Cobol85Kindperformby:"performby",
	Cobol85Kindperformtestclause:"performtestclause",
	Cobol85Kindpurgestatement:"purgestatement",
	Cobol85Kindreadstatement:"readstatement",
	Cobol85Kindreadinto:"readinto",
	Cobol85Kindreadwith:"readwith",
	Cobol85Kindreadkey:"readkey",
	Cobol85Kindreceivestatement:"receivestatement",
	Cobol85Kindreceivefromstatement:"receivefromstatement",
	Cobol85Kindreceivefrom:"receivefrom",
	Cobol85Kindreceiveintostatement:"receiveintostatement",
	Cobol85Kindreceivenodata:"receivenodata",
	Cobol85Kindreceivewithdata:"receivewithdata",
	Cobol85Kindreceivebefore:"receivebefore",
	Cobol85Kindreceivewith:"receivewith",
	Cobol85Kindreceivethread:"receivethread",
	Cobol85Kindreceivesize:"receivesize",
	Cobol85Kindreceivestatus:"receivestatus",
	Cobol85Kindreleasestatement:"releasestatement",
	Cobol85Kindreturnstatement:"returnstatement",
	Cobol85Kindreturninto:"returninto",
	Cobol85Kindrewritestatement:"rewritestatement",
	Cobol85Kindrewritefrom:"rewritefrom",
	Cobol85Kindsearchstatement:"searchstatement",
	Cobol85Kindsearchvarying:"searchvarying",
	Cobol85Kindsearchwhen:"searchwhen",
	Cobol85Kindsendstatement:"sendstatement",
	Cobol85Kindsendstatementsync:"sendstatementsync",
	Cobol85Kindsendstatementasync:"sendstatementasync",
	Cobol85Kindsendfromphrase:"sendfromphrase",
	Cobol85Kindsendwithphrase:"sendwithphrase",
	Cobol85Kindsendreplacingphrase:"sendreplacingphrase",
	Cobol85Kindsendadvancingphrase:"sendadvancingphrase",
	Cobol85Kindsendadvancingpage:"sendadvancingpage",
	Cobol85Kindsendadvancinglines:"sendadvancinglines",
	Cobol85Kindsendadvancingmnemonic:"sendadvancingmnemonic",
	Cobol85Kindsetstatement:"setstatement",
	Cobol85Kindsettostatement:"settostatement",
	Cobol85Kindsetupdownbystatement:"setupdownbystatement",
	Cobol85Kindsetto:"setto",
	Cobol85Kindsettovalue:"settovalue",
	Cobol85Kindsetbyvalue:"setbyvalue",
	Cobol85Kindsortstatement:"sortstatement",
	Cobol85Kindsortonkeyclause:"sortonkeyclause",
	Cobol85Kindsortduplicatesphrase:"sortduplicatesphrase",
	Cobol85Kindsortcollatingsequencephrase:"sortcollatingsequencephrase",
	Cobol85Kindsortcollatingalphanumeric:"sortcollatingalphanumeric",
	Cobol85Kindsortcollatingnational:"sortcollatingnational",
	Cobol85Kindsortinputprocedurephrase:"sortinputprocedurephrase",
	Cobol85Kindsortinputthrough:"sortinputthrough",
	Cobol85Kindsortusing:"sortusing",
	Cobol85Kindsortoutputprocedurephrase:"sortoutputprocedurephrase",
	Cobol85Kindsortoutputthrough:"sortoutputthrough",
	Cobol85Kindsortgivingphrase:"sortgivingphrase",
	Cobol85Kindsortgiving:"sortgiving",
	Cobol85Kindstartstatement:"startstatement",
	Cobol85Kindstartkey:"startkey",
	Cobol85Kindstopstatement:"stopstatement",
	Cobol85Kindstringstatement:"stringstatement",
	Cobol85Kindstringsendingphrase:"stringsendingphrase",
	Cobol85Kindstringsending:"stringsending",
	Cobol85Kindstringdelimitedbyphrase:"stringdelimitedbyphrase",
	Cobol85Kindstringforphrase:"stringforphrase",
	Cobol85Kindstringintophrase:"stringintophrase",
	Cobol85Kindstringwithpointerphrase:"stringwithpointerphrase",
	Cobol85Kindsubtractstatement:"subtractstatement",
	Cobol85Kindsubtractfromstatement:"subtractfromstatement",
	Cobol85Kindsubtractfromgivingstatement:"subtractfromgivingstatement",
	Cobol85Kindsubtractcorrespondingstatement:"subtractcorrespondingstatement",
	Cobol85Kindsubtractsubtrahend:"subtractsubtrahend",
	Cobol85Kindsubtractminuend:"subtractminuend",
	Cobol85Kindsubtractminuendgiving:"subtractminuendgiving",
	Cobol85Kindsubtractgiving:"subtractgiving",
	Cobol85Kindsubtractminuendcorresponding:"subtractminuendcorresponding",
	Cobol85Kindterminatestatement:"terminatestatement",
	Cobol85Kindunstringstatement:"unstringstatement",
	Cobol85Kindunstringsendingphrase:"unstringsendingphrase",
	Cobol85Kindunstringdelimitedbyphrase:"unstringdelimitedbyphrase",
	Cobol85Kindunstringorallphrase:"unstringorallphrase",
	Cobol85Kindunstringintophrase:"unstringintophrase",
	Cobol85Kindunstringinto:"unstringinto",
	Cobol85Kindunstringdelimiterin:"unstringdelimiterin",
	Cobol85Kindunstringcountin:"unstringcountin",
	Cobol85Kindunstringwithpointerphrase:"unstringwithpointerphrase",
	Cobol85Kindunstringtallyingphrase:"unstringtallyingphrase",
	Cobol85Kindusestatement:"usestatement",
	Cobol85Kinduseafterclause:"useafterclause",
	Cobol85Kinduseafteron:"useafteron",
	Cobol85Kindusedebugclause:"usedebugclause",
	Cobol85Kindusedebugon:"usedebugon",
	Cobol85Kindwritestatement:"writestatement",
	Cobol85Kindwritefromphrase:"writefromphrase",
	Cobol85Kindwriteadvancingphrase:"writeadvancingphrase",
	Cobol85Kindwriteadvancingpage:"writeadvancingpage",
	Cobol85Kindwriteadvancinglines:"writeadvancinglines",
	Cobol85Kindwriteadvancingmnemonic:"writeadvancingmnemonic",
	Cobol85Kindwriteatendofpagephrase:"writeatendofpagephrase",
	Cobol85Kindwritenotatendofpagephrase:"writenotatendofpagephrase",
	Cobol85Kindatendphrase:"atendphrase",
	Cobol85Kindnotatendphrase:"notatendphrase",
	Cobol85Kindinvalidkeyphrase:"invalidkeyphrase",
	Cobol85Kindnotinvalidkeyphrase:"notinvalidkeyphrase",
	Cobol85Kindonoverflowphrase:"onoverflowphrase",
	Cobol85Kindnotonoverflowphrase:"notonoverflowphrase",
	Cobol85Kindonsizeerrorphrase:"onsizeerrorphrase",
	Cobol85Kindnotonsizeerrorphrase:"notonsizeerrorphrase",
	Cobol85Kindonexceptionclause:"onexceptionclause",
	Cobol85Kindnotonexceptionclause:"notonexceptionclause",
	Cobol85Kindarithmeticexpression:"arithmeticexpression",
	Cobol85Kindplusminus:"plusminus",
	Cobol85Kindmultdivs:"multdivs",
	Cobol85Kindmultdiv:"multdiv",
	Cobol85Kindpowers:"powers",
	Cobol85Kindpower:"power",
	Cobol85Kindbasis:"basis",
	Cobol85Kindcondition:"condition",
	Cobol85Kindandorcondition:"andorcondition",
	Cobol85Kindcombinablecondition:"combinablecondition",
	Cobol85Kindsimplecondition:"simplecondition",
	Cobol85Kindclasscondition:"classcondition",
	Cobol85Kindconditionnamereference:"conditionnamereference",
	Cobol85Kindconditionnamesubscriptreference:"conditionnamesubscriptreference",
	Cobol85Kindrelationcondition:"relationcondition",
	Cobol85Kindrelationsigncondition:"relationsigncondition",
	Cobol85Kindrelationarithmeticcomparison:"relationarithmeticcomparison",
	Cobol85Kindrelationcombinedcomparison:"relationcombinedcomparison",
	Cobol85Kindrelationcombinedcondition:"relationcombinedcondition",
	Cobol85Kindrelationaloperator:"relationaloperator",
	Cobol85Kindabbreviation:"abbreviation",
	Cobol85Kindidentifier:"identifier",
	Cobol85Kindtablecall:"tablecall",
	Cobol85Kindfunctioncall:"functioncall",
	Cobol85Kindreferencemodifier:"referencemodifier",
	Cobol85Kindcharacterposition:"characterposition",
	Cobol85Kindlength:"length",
	Cobol85Kindsubscript:"subscript",
	Cobol85Kindargument:"argument",
	Cobol85Kindqualifieddataname:"qualifieddataname",
	Cobol85Kindqualifieddatanameformat1:"qualifieddatanameformat1",
	Cobol85Kindqualifieddatanameformat2:"qualifieddatanameformat2",
	Cobol85Kindqualifieddatanameformat3:"qualifieddatanameformat3",
	Cobol85Kindqualifieddatanameformat4:"qualifieddatanameformat4",
	Cobol85Kindqualifiedindata:"qualifiedindata",
	Cobol85Kindindata:"indata",
	Cobol85Kindinfile:"infile",
	Cobol85Kindinmnemonic:"inmnemonic",
	Cobol85Kindinsection:"insection",
	Cobol85Kindinlibrary:"inlibrary",
	Cobol85Kindintable:"intable",
	Cobol85Kindalphabetname:"alphabetname",
	Cobol85Kindassignmentname:"assignmentname",
	Cobol85Kindbasisname:"basisname",
	Cobol85Kindcdname:"cdname",
	Cobol85Kindclassname:"classname",
	Cobol85Kindcomputername:"computername",
	Cobol85Kindconditionname:"conditionname",
	Cobol85Kinddataname:"dataname",
	Cobol85Kinddatadescname:"datadescname",
	Cobol85Kindenvironmentname:"environmentname",
	Cobol85Kindfilename:"filename",
	Cobol85Kindfunctionname:"functionname",
	Cobol85Kindindexname:"indexname",
	Cobol85Kindlanguagename:"languagename",
	Cobol85Kindlibraryname:"libraryname",
	Cobol85Kindlocalname:"localname",
	Cobol85Kindmnemonicname:"mnemonicname",
	Cobol85Kindparagraphname:"paragraphname",
	Cobol85Kindprocedurename:"procedurename",
	Cobol85Kindprogramname:"programname",
	Cobol85Kindrecordname:"recordname",
	Cobol85Kindreportname:"reportname",
	Cobol85Kindroutinename:"routinename",
	Cobol85Kindscreenname:"screenname",
	Cobol85Kindsectionname:"sectionname",
	Cobol85Kindsystemname:"systemname",
	Cobol85Kindsymboliccharacter:"symboliccharacter",
	Cobol85Kindtextname:"textname",
	Cobol85Kindcobolword:"cobolword",
	Cobol85Kindliteral:"literal",
	Cobol85Kindbooleanliteral:"booleanliteral",
	Cobol85Kindnumericliteral:"numericliteral",
	Cobol85Kindintegerliteral:"integerliteral",
	Cobol85Kindcicsdfhrespliteral:"cicsdfhrespliteral",
	Cobol85Kindcicsdfhvalueliteral:"cicsdfhvalueliteral",
	Cobol85Kindfigurativeconstant:"figurativeconstant",
	Cobol85Kindspecialregister:"specialregister",
	Cobol85Kindcommententry:"commententry",
}

