// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fast_

import (
	flatbuffers "github.com/google/flatbuffers/go"

	fast___Graph_ "fast_/Graph_"
)

type Graph struct {
	_tab flatbuffers.Table
}

func GetRootAsGraph(buf []byte, offset flatbuffers.UOffsetT) *Graph {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Graph{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Graph) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Graph) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Graph) Unit(obj *fast___Graph_.Unit, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Graph) UnitLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GraphStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GraphAddUnit(builder *flatbuffers.Builder, unit flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(unit), 0)
}
func GraphStartUnitVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GraphEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
