// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fast_

import (
	flatbuffers "github.com/google/flatbuffers/go"

	fast___Pairs_ "fast_/Pairs_"
)

type Pairs struct {
	_tab flatbuffers.Table
}

func GetRootAsPairs(buf []byte, offset flatbuffers.UOffsetT) *Pairs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Pairs{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Pairs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Pairs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Pairs) Pair(obj *fast___Pairs_.Pair, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Pairs) PairLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PairsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PairsAddPair(builder *flatbuffers.Builder, pair flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(pair), 0)
}
func PairsStartPairVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PairsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
