// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Pair_

type CloneType = int32
const (
	CloneTypeMAYBE CloneType = 0
	CloneTypeYES CloneType = 1
	CloneTypeNO CloneType = 2
)

var EnumNamesCloneType = map[CloneType]string{
	CloneTypeMAYBE:"MAYBE",
	CloneTypeYES:"YES",
	CloneTypeNO:"NO",
}

