// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Diff_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Add struct {
	_tab flatbuffers.Table
}

func GetRootAsAdd(buf []byte, offset flatbuffers.UOffsetT) *Add {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Add{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Add) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Add) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Add) Src() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Add) MutateSrc(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Add) Dst() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Add) MutateDst(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *Add) Position() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Add) MutatePosition(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func AddStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AddAddSrc(builder *flatbuffers.Builder, src int32) {
	builder.PrependInt32Slot(0, src, 0)
}
func AddAddDst(builder *flatbuffers.Builder, dst int32) {
	builder.PrependInt32Slot(1, dst, 0)
}
func AddAddPosition(builder *flatbuffers.Builder, position int32) {
	builder.PrependInt32Slot(2, position, 0)
}
func AddEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
