// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Diff_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Del struct {
	_tab flatbuffers.Table
}

func GetRootAsDel(buf []byte, offset flatbuffers.UOffsetT) *Del {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Del{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Del) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Del) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Del) Src() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Del) MutateSrc(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func DelStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DelAddSrc(builder *flatbuffers.Builder, src int32) {
	builder.PrependInt32Slot(0, src, 0)
}
func DelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
