// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Diff_

type DeltaType = int32
const (
	DeltaTypeMATCH DeltaType = 0
	DeltaTypeADD DeltaType = 1
	DeltaTypeDEL DeltaType = 2
	DeltaTypeMOVE DeltaType = 3
	DeltaTypeUPDATE DeltaType = 4
)

var EnumNamesDeltaType = map[DeltaType]string{
	DeltaTypeMATCH:"MATCH",
	DeltaTypeADD:"ADD",
	DeltaTypeDEL:"DEL",
	DeltaTypeMOVE:"MOVE",
	DeltaTypeUPDATE:"UPDATE",
}

