// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Diff_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Move struct {
	_tab flatbuffers.Table
}

func GetRootAsMove(buf []byte, offset flatbuffers.UOffsetT) *Move {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Move{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Move) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Move) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Move) Src() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Move) MutateSrc(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Move) Dst() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Move) MutateDst(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *Move) Position() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Move) MutatePosition(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func MoveStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MoveAddSrc(builder *flatbuffers.Builder, src int32) {
	builder.PrependInt32Slot(0, src, 0)
}
func MoveAddDst(builder *flatbuffers.Builder, dst int32) {
	builder.PrependInt32Slot(1, dst, 0)
}
func MoveAddPosition(builder *flatbuffers.Builder, position int32) {
	builder.PrependInt32Slot(2, position, 0)
}
func MoveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
