// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Diff_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Update struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdate(buf []byte, offset flatbuffers.UOffsetT) *Update {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Update{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Update) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Update) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Update) Src() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Update) MutateSrc(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Update) Dst() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Update) MutateDst(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func UpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UpdateAddSrc(builder *flatbuffers.Builder, src int32) {
	builder.PrependInt32Slot(0, src, 0)
}
func UpdateAddDst(builder *flatbuffers.Builder, dst int32) {
	builder.PrependInt32Slot(1, dst, 0)
}
func UpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
