// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Element_

type DiffType = int32
const (
	DiffTypeMATCHED DiffType = 0
	DiffTypeADDED DiffType = 1
	DiffTypeDELETED DiffType = 2
	DiffTypeCHANGED_FROM DiffType = 3
	DiffTypeCHANGED_TO DiffType = 4
)

var EnumNamesDiffType = map[DiffType]string{
	DiffTypeMATCHED:"MATCHED",
	DiffTypeADDED:"ADDED",
	DiffTypeDELETED:"DELETED",
	DiffTypeCHANGED_FROM:"CHANGED_FROM",
	DiffTypeCHANGED_TO:"CHANGED_TO",
}

