// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Element_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Literal struct {
	_tab flatbuffers.Table
}

func GetRootAsLiteral(buf []byte, offset flatbuffers.UOffsetT) *Literal {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Literal{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Literal) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Literal) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Literal) Type() LiteralType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Literal) MutateType(n LiteralType) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func LiteralStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LiteralAddType(builder *flatbuffers.Builder, type_ int32) {
	builder.PrependInt32Slot(0, type_, 0)
}
func LiteralEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
