// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Log_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Author struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthor(buf []byte, offset flatbuffers.UOffsetT) *Author {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Author{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Author) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Author) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Author) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Author) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Author) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Author) Email() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AuthorStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AuthorAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func AuthorAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func AuthorAddEmail(builder *flatbuffers.Builder, email flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(email), 0)
}
func AuthorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
