// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Graph_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Edge struct {
	_tab flatbuffers.Table
}

func GetRootAsEdge(buf []byte, offset flatbuffers.UOffsetT) *Edge {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Edge{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Edge) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Edge) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Edge) Node1() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Edge) MutateNode1(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Edge) Node2() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Edge) MutateNode2(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func EdgeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EdgeAddNode1(builder *flatbuffers.Builder, node1 int32) {
	builder.PrependInt32Slot(0, node1, 0)
}
func EdgeAddNode2(builder *flatbuffers.Builder, node2 int32) {
	builder.PrependInt32Slot(1, node2, 0)
}
func EdgeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
