// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Graph_

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NodeType struct {
	_tab flatbuffers.Table
}

func GetRootAsNodeType(buf []byte, offset flatbuffers.UOffsetT) *NodeType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NodeType{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NodeType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NodeType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NodeType) Node() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NodeType) MutateNode(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *NodeType) Type() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NodeTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NodeTypeAddNode(builder *flatbuffers.Builder, node int32) {
	builder.PrependInt32Slot(0, node, 0)
}
func NodeTypeAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(type_), 0)
}
func NodeTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
